
import "./globals.css";
import { BaseUrlProvider } from "./BASEURLContext";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <BaseUrlProvider>
          {children}
        </BaseUrlProvider>
      </body>
    </html>
  );
}



